BaoMing/Controllers/BaoMingController.cs
using BaoMing.Models;
using System.Web.Mvc;

namespace BaoMing.Controllers
{
    public class BaoMingController : Controller
    {
        // GET: BaoMing
        public ActionResult Index()
        {
            return View();
        }

        #region ghy
        // GET: ghy
        public ActionResult Ghy()
        {
            return View();
        }

        // Post: ghy
        [HttpPost]
        public ActionResult Ghy(GhyModels models)
        {
            ExcelManage eM = new ExcelManage();

            if (ModelState.IsValid)
            {
                if (Authentication.ghy_IsZhiYuan(models) == false)
                {
                    ModelState.AddModelError("ZhiYuan", "至少选择一项志愿部门/子网");
                    return View(models);
                }
                if (eM.SavetoExcel(models,"ghy_BaoMing"))
                {
                    return Content("<script>alert('报名成功');window.location.href='/';</script>");
                }
                else
                {
                    ModelState.AddModelError("execl_err", "excel操作失败");
                }
            }
            ModelState.AddModelError("", "报名失败!请按要求填写");
            return View(models);
        }
        #endregion

        #region 校报记者团
        // GET: Xbjzt
        public ActionResult Xbjzt()
        {
            return View();
        }

        // Post: Xbjzt
        [HttpPost]
        public ActionResult Xbjzt(XbjztModels models)
        {
            ExcelManage eM = new ExcelManage();

            if (ModelState.IsValid)
            {
                if (Authentication.xbjzt_IsYiXiang(models) == false)
                {
                    ModelState.AddModelError("yixiang", "至少选择一项意向组别");
                    return View(models);
                }
                if (eM.SavetoExcel(models, "xbjzt_BaoMing"))
                {
                    //return Content("<script>alert('报名成功');window.location.href='http://ghy.swufe.edu.cn/aboutus';</script>");
                    return Content("<script>alert('报名成功');window.location.href='/';</script>");
                }
            }
            ModelState.AddModelError("", "报名失败!请按要求填写");
            return View(models);
        }
        #endregion

        #region 校园文化研究社
        // GET: Xywh
        public ActionResult Xywh()
        {
            return View();
        }

        // Post: Xywh
        [HttpPost]
        public ActionResult Xywh(XywhModels models)
        {
            ExcelManage eM = new ExcelManage();

            if (ModelState.IsValid)
            {
                if (Authentication.xywh_IsYiXiang(models) == false)
                {
                    ModelState.AddModelError("yixiang", "至少选择一项意向部门");
                    return View(models);
                }
                if (eM.SavetoExcel(models, "xywh_BaoMing"))
                {
                    //return Content("<script>alert('报名成功');window.location.href='http://ghy.swufe.edu.cn/aboutus';</script>");
                    return Content("<script>alert('报名成功');window.location.href='/';</script>");
                }
            }
            ModelState.AddModelError("", "报名失败!请按要求填写");
            return View(models);
        }
        #endregion

        #region 新媒体中心
        // GET: Xmtzx
        public ActionResult Xmtzx()
        {
            return View();
        }

        // Post: Xmtzx
        [HttpPost]
        public ActionResult Xmtzx(XmtzxModels models)
        {
            ExcelManage eM = new ExcelManage();

            if (ModelState.IsValid)
            {
                if (eM.SavetoExcel(models, "xmtzx_BaoMing"))
                {
                    //return Content("<script>alert('报名成功');window.location.href='http://ghy.swufe.edu.cn/aboutus';</script>");
                    return Content("<script>alert('报名成功');window.location.href='/';</script>");
                }
            }
            ModelState.AddModelError("", "报名失败!请按要求填写");
            return View(models);
        }
        #endregion

        #region 西财之声广播站
        // GET: Xczs
        public ActionResult Xczs()
        {
            return View();
        }

        // Post: Xywh
        [HttpPost]
        public ActionResult Xczs(XczsModels models)
        {
            ExcelManage eM = new ExcelManage();

            if (ModelState.IsValid)
            {
                if (Authentication.xczs_IsYiXiang(models) == false)
                {
                    ModelState.AddModelError("yixiang", "至少选择一项意向部门");
                    return View(models);
                }
                if (eM.SavetoExcel(models, "xczs_BaoMing"))
                {
                    //return Content("<script>alert('报名成功');window.location.href='http://ghy.swufe.edu.cn/aboutus';</script>");
                    return Content("<script>alert('报名成功');window.location.href='/';</script>");
                }
            }
            ModelState.AddModelError("", "报名失败!请按要求填写");
            return View(models);
        }
        #endregion
    }
}

BaoMing/Views/BaoMing/Index.cshtml
@{
    Layout = "~/Views/Shared/_Layout_index.cshtml";
    ViewBag.Title = "简历投递";
}
<div class="main-z">
    <div class="row">
        <div class="bm">
			<div class="bm_block" data-bm="ghy">
                <a class="bm_href" href="~/BaoMing/ghy">
                    <div class="bm_logo">
                        <img src="~/img/ghy_logo_small.png">
                    </div>
                    <p>光华园网站</p>
                </a>
            </div>
            <div class="bm_block" data-bm="xbjzt">
                <a class="bm_href" href="~/BaoMing/xbjzt">
                    <div class="bm_logo">
                        <img src="~/img/xbjzt_logo.jpg">
                    </div>
                    <p>校报记者团</p>
                </a>
            </div>
            <div class="bm_block" data-bm="xczs">
                <a class="bm_href" href="~/BaoMing/xczs">
                    <div class="bm_logo">
                        <img src="~/img/xczs_logo.png">
                    </div>
                    <p>西财之声广播站</p>
                </a>
            </div>
            <div class="bm_block" data-bm="xmtzx">
                <a class="bm_href" href="~/BaoMing/xmtzx">
                    <div class="bm_logo">
                        <img src="~/img/xmtzx_logo.png">
                    </div>
                    <p>新媒体中心</p>
                </a>
            </div>
            <div class="bm_block" data-bm="xywh">
                <a class="bm_href" href="~/BaoMing/xywh">
                    <div class="bm_logo">
                        <img src="~/img/xywh_logo.png">
                    </div>
                    <p>校园文化研究社</p>
                </a>
            </div>
        </div>
    </div>
</div>

BaoMing/Views/BaoMing/ghy.cshtml
@model BaoMing.Models.GhyModels
@{
    ViewBag.Title = "光华园-简历投递";
}
<div class="main-z">
    <div class="row">
        <div class="know1 col-md-12">
            <div class="knowUs">
                光华园-简历投递<span>加 * 的为必填项</span>
            </div>
            <div class="knowUs1">
                SUBMITING RESUME
            </div>
            <div class="know-line">
            </div>
        </div>
    </div>
    <div class="row submit-content">
        <div class="col-md-12">
            @using (Html.BeginForm("ghy", "BaoMing", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
            {
                <h3 class="bm_title_3">
                    个人信息
                </h3>
                <div class="form-group">
                    @Html.LabelFor(m => m.Name, new { @class = "col-md-2 col-xs-3 control-label bm_lable_in" })
                    <div class="col-md-10  col-xs-9">
                        @Html.EditorFor(m => m.Name, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(m => m.Name, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.Sex, new { @class = "col-md-2 col-xs-3 control-label bm_lable_in" })
                    <div class="col-md-10 col-xs-9">
                        @Html.EditorFor(m => m.Sex, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(m => m.Sex, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.Birth, new { @class = "col-md-2 col-xs-3 control-label bm_lable_in" })
                    <div class="col-md-10 col-xs-9">
                        @*@Html.EditorFor(m => m.Birth, new { htmlAttributes = new { @class = "form-control" } })*@
                        @Html.TextBoxFor(m => m.Birth, new { @class = "form-control",type="date" })
                        @Html.ValidationMessageFor(m => m.Birth, "", new { @class = "text-danger" })
                    </div>
                </div>
                @*<div class="form-group">
                        @Html.LabelFor(m => m.NativePlace, new { @class = "col-md-2 col-xs-3 control-label" })
                        <div class="col-md-10">
                            @Html.EditorFor(m => m.NativePlace, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(m => m.NativePlace, "", new { @class = "text-danger" })
                        </div>
                    </div>*@
                <div class="form-group">
                    @Html.LabelFor(m => m.Grademajor, new { @class = "col-md-2 col-xs-3 control-label bm_lable_in" })
                    <div class="col-md-10 col-xs-9">
                        @Html.EditorFor(m => m.Grademajor, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(m => m.Grademajor, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.QQ, new { @class = "col-md-2 col-xs-3 control-label bm_lable_in" })
                    <div class="col-md-10 col-xs-9">
                        @Html.EditorFor(m => m.QQ, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(m => m.QQ, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.Email, new { @class = "col-md-2 col-xs-3 control-label bm_lable_in" })
                    <div class="col-md-10 col-xs-9">
                        @Html.EditorFor(m => m.Email, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(m => m.Email, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.Phone, new { @class = "col-md-2 col-xs-3 control-label bm_lable_in" })
                    <div class="col-md-10 col-xs-9">
                        @Html.EditorFor(m => m.Phone, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(m => m.Phone, "", new { @class = "text-danger" })
                    </div>
                </div>
                <h3 class="bm_title_3">
                    志愿部门/子网(可以多选哦):
                </h3>
                //提示志愿部门/子网未被选中
                @Html.ValidationMessage("ZhiYuan", "", new { @class = "text-danger" })
                <div class="zhiyuan-k col-md-12">
                    <div class="zhiyuan-p col-md-3 col-sm-6 col-xs-12">
                        @Html.CheckBoxFor(m => m.She.Checked, new { @class = "form-control chk"})
                        <label class="control-label chk_label" for="She_Checked"></label>
                        @Html.LabelFor(m => m.She, new { @class = "control-label" })
                    </div>
                    <div class="zhiyuan-p col-md-3 col-sm-6 col-xs-12">
                        @Html.CheckBoxFor(m => m.Kai.Checked, new { @class = "form-control chk" })
                        <label class="control-label chk_label" for="Kai_Checked"></label>
                        @Html.LabelFor(m => m.Kai, new { @class = "control-label" })
                    </div>
                    <div class="zhiyuan-p col-md-3 col-sm-6 col-xs-12">
                        @Html.CheckBoxFor(m => m.Ban.Checked, new { @class = "form-control chk" })
                        <label class="control-label chk_label" for="Ban_Checked"></label>
                        @Html.LabelFor(m => m.Ban, new { @class = "control-label" })
                    </div>
                    <div class="zhiyuan-p col-md-3 col-sm-6 col-xs-12">
                        @Html.CheckBoxFor(m => m.Xin.Checked, new { @class = "form-control chk" })
                        <label class="control-label chk_label" for="Xin_Checked"></label>
                        @Html.LabelFor(m => m.Xin, new { @class = "control-label" })
                    </div>
                    <div class="zhiyuan-p col-md-3 col-sm-6 col-xs-12">
                        @Html.CheckBoxFor(m => m.Yin.Checked, new { @class = "form-control chk" })
                        <label class="control-label chk_label" for="Yin_Checked"></label>
                        @Html.LabelFor(m => m.Yin, new { @class = "control-label" })
                    </div>
                    <div class="zhiyuan-p col-md-3 col-sm-6 col-xs-12">
                        @Html.CheckBoxFor(m => m.Sheng.Checked, new { @class = "form-control chk" })
                        <label class="control-label chk_label" for="Sheng_Checked"></label>
                        @Html.LabelFor(m => m.Sheng, new { @class = "control-label" })
                    </div>
                    <div class="zhiyuan-p  col-md-3 col-sm-6 col-xs-12">
                        @Html.CheckBoxFor(m => m.Ruan.Checked, new { @class = "form-control chk" })
                        <label class="control-label chk_label" for="Ruan_Checked"></label>
                        @Html.LabelFor(m => m.Ruan, new { @class = "control-label" })
                    </div>
                    <div class="zhiyuan-p col-md-3 col-sm-6 col-xs-12">
                        @Html.CheckBoxFor(m => m.Xue.Checked, new { @class = "form-control chk" })
                        <label class="control-label chk_label" for="Xue_Checked"></label>
                        @Html.LabelFor(m => m.Xue, new { @class = "control-label" })
                    </div>
                    <div class="zhiyuan-p col-md-3 col-sm-6 col-xs-12">
                        @Html.CheckBoxFor(m => m.Dian.Checked, new { @class = "form-control chk" })
                        <label class="control-label chk_label" for="Dian_Checked"></label>
                        @Html.LabelFor(m => m.Dian, new { @class = "control-label" })
                    </div>
                    <div class="zhiyuan-p col-md-3 col-sm-6 col-xs-12">
                        @Html.CheckBoxFor(m => m.Zi.Checked, new { @class = "form-control chk" })
                        <label class="control-label chk_label" for="Zi_Checked"></label>
                        @Html.LabelFor(m => m.Zi, new { @class = "control-label" })
                    </div>
                    <div class="zhiyuan-p col-md-3 col-sm-6 col-xs-12">
                        @Html.CheckBoxFor(m => m.Shi.Checked, new { @class = "form-control chk" })
                        <label class="control-label chk_label" for="Shi_Checked"></label>
                        @Html.LabelFor(m => m.Shi, new { @class = "control-label" })
                    </div>
                </div>
                <h3 class="bm_title_3">
                    你为什么想加入光华园:
                </h3>
                <div class="zhiyuan-p zhiyuan-textarea col-md-12">
                    @Html.TextAreaFor(m => m.TeChang, new { @class = "form-control", rows = "4", cols = "5" })
                    @Html.ValidationMessageFor(m => m.TeChang, "", new { @class = "text-danger" })
                </div>

                <div class="form-group" id="submit">
                    <div class="col-md-offset-1 col-md-2">
                        <input type="submit" class="btn btn-default" value="提交" />
                    </div>
                </div>
            }
        </div>
    </div>
</div>

BaoMing/Views/BaoMing/xbjzt.cshtml
@model BaoMing.Models.XbjztModels
@{
    ViewBag.Title = "校报记者团-简历投递";
}
<div class="main-z">
    <div class="row">
        <div class="know1 col-md-12">
            <div class="knowUs">
                校报记者团-简历投递<span>加 * 的为必填项</span>
            </div>
            <div class="knowUs1">
                SUBMITING RESUME
            </div>
            <div class="know-line">
            </div>
        </div>
    </div>
    <div class="row submit-content">
        <div class="col-md-12">
            @using (Html.BeginForm("Xbjzt", "BaoMing", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
            {
                <h3 class="bm_title_3">
                    个人信息
                </h3>
                <div class="form-group">
                    @Html.LabelFor(m => m.Name, new { @class = "col-md-2 col-xs-3 control-label bm_lable_in" })
                    <div class="col-md-10  col-xs-9">
                        @Html.EditorFor(m => m.Name, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(m => m.Name, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.Sex, new { @class = "col-md-2 col-xs-3 control-label bm_lable_in" })
                    <div class="col-md-10  col-xs-9">
                        @Html.EditorFor(m => m.Sex, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(m => m.Sex, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.Department, new { @class = "col-md-2 col-xs-3 control-label bm_lable_in" })
                    <div class="col-md-10  col-xs-9">
                        @Html.EditorFor(m => m.Department, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(m => m.Department, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.Phone, new { @class = "col-md-2 col-xs-3 control-label bm_lable_in" })
                    <div class="col-md-10  col-xs-9">
                        @Html.EditorFor(m => m.Phone, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(m => m.Phone, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.QQ, new { @class = "col-md-2 col-xs-3 control-label bm_lable_in" })
                    <div class="col-md-10  col-xs-9">
                        @Html.EditorFor(m => m.QQ, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(m => m.QQ, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.TeChang, new { @class = "col-md-2 col-xs-3 control-label bm_lable_in" })
                    <div class="col-md-10  col-xs-9">
                        @Html.EditorFor(m => m.TeChang, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(m => m.TeChang, "", new { @class = "text-danger" })
                    </div>
                </div>

                <h3 class="bm_title_3">
                    意向组别:
                </h3>
                //提示意向部门未被选中
                @Html.ValidationMessage("yixiang", "", new { @class = "text-danger" })
                <div class="zhiyuan-k col-md-12">
                    <div class="zhiyuan-p col-md-3 col-sm-6 col-xs-12">
                        @Html.CheckBoxFor(m => m.WenZi.Checked, new { @class = "form-control chk" })
                        <label class="control-label chk_label" for="WenZi_Checked"></label>
                        @Html.LabelFor(m => m.WenZi, new { @class = "control-label" })
                    </div>
                    <div class="zhiyuan-p col-md-3 col-sm-6 col-xs-12">
                        @Html.CheckBoxFor(m => m.SheYing.Checked, new { @class = "form-control chk" })
                        <label class="control-label chk_label" for="SheYing_Checked"></label>
                        @Html.LabelFor(m => m.SheYing, new { @class = "control-label" })
                    </div>
                    <div class="zhiyuan-p col-md-3 col-sm-6 col-xs-12">
                        @Html.CheckBoxFor(m => m.MeiBian.Checked, new { @class = "form-control chk" })
                        <label class="control-label chk_label" for="MeiBian_Checked"></label>
                        @Html.LabelFor(m => m.MeiBian, new { @class = "control-label" })
                    </div>
                    <div class="zhiyuan-p col-md-3 col-sm-6 col-xs-12">
                        @Html.CheckBoxFor(m => m.WangLuo.Checked, new { @class = "form-control chk" })
                        <label class="control-label chk_label" for="WangLuo_Checked"></label>
                        @Html.LabelFor(m => m.WangLuo, new { @class = "control-label" })
                    </div>
                </div>
               
                <h3 class="bm_title_3">
                    自我介绍:
                </h3>
                <div class="zhiyuan-p zhiyuan-textarea col-md-12">
                    @Html.TextAreaFor(m => m.JianJie, new { @class = "form-control", rows = "4", cols = "5" })
                    @Html.ValidationMessageFor(m => m.JianJie, "", new { @class = "text-danger" })
                </div>
                <div class="form-group" id="submit">
                    <div class="col-md-offset-1 col-md-2">
                        <input type="submit" class="btn btn-default" value="提交" />
                    </div>
                </div>
            }
        </div>
    </div>
</div>

BaoMing/Views/BaoMing/xczs.cshtml
@model BaoMing.Models.XczsModels
@{
    ViewBag.Title = "西财之声-简历投递";
}
<div class="main-z">
    <div class="row">
        <div class="know1 col-md-12">
            <div class="knowUs">
                西财之声-简历投递<span>加 * 的为必填项</span>
            </div>
            <div class="knowUs1">
                SUBMITING RESUME
            </div>
            <div class="know-line">
            </div>
        </div>
    </div>
    <div class="row submit-content">
        <div class="col-md-12">
            @using (Html.BeginForm("Xczs", "BaoMing", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
            {
                <h3 class="bm_title_3">
                    个人信息
                </h3>
                <div class="form-group">
                    @Html.LabelFor(m => m.Name, new { @class = "col-md-2 col-xs-3 control-label bm_lable_in" })
                    <div class="col-md-10  col-xs-9">
                        @Html.EditorFor(m => m.Name, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(m => m.Name, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.Sex, new { @class = "col-md-2 col-xs-3 control-label bm_lable_in" })
                    <div class="col-md-10 col-xs-9">
                        @Html.EditorFor(m => m.Sex, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(m => m.Sex, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.Grademajor, new { @class = "col-md-2 col-xs-3 control-label bm_lable_in" })
                    <div class="col-md-10 col-xs-9">
                        @Html.EditorFor(m => m.Grademajor, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(m => m.Grademajor, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.Phone, new { @class = "col-md-2 col-xs-3 control-label bm_lable_in" })
                    <div class="col-md-10 col-xs-9">
                        @Html.EditorFor(m => m.Phone, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(m => m.Phone, "", new { @class = "text-danger" })
                    </div>
                </div>
                <h3 class="bm_title_3">
                    意向部门(可以多选哦):
                </h3>
                //提示意向部门未被选中
                @Html.ValidationMessage("yixiang", "", new { @class = "text-danger" })
                <div class="zhiyuan-k col-md-12">
                    <div class="zhiyuan-p col-md-3 col-sm-6 col-xs-12">
                        @Html.CheckBoxFor(m => m.BoYin.Checked, new { @class = "form-control chk" })
                        <label class="control-label chk_label" for="BoYin_Checked"></label>
                        @Html.LabelFor(m => m.BoYin, new { @class = "control-label" })
                    </div>
                    <div class="zhiyuan-p col-md-3 col-sm-6 col-xs-12">
                        @Html.CheckBoxFor(m => m.WaiLian.Checked, new { @class = "form-control chk" })
                        <label class="control-label chk_label" for="WaiLian_Checked"></label>
                        @Html.LabelFor(m => m.WaiLian, new { @class = "control-label" })
                    </div>
                    <div class="zhiyuan-p col-md-3 col-sm-6 col-xs-12">
                        @Html.CheckBoxFor(m => m.BianJi.Checked, new { @class = "form-control chk" })
                        <label class="control-label chk_label" for="BianJi_Checked"></label>
                        @Html.LabelFor(m => m.BianJi, new { @class = "control-label" })
                    </div>
                    <div class="zhiyuan-p col-md-3 col-sm-6 col-xs-12">
                        @Html.CheckBoxFor(m => m.XuanChuan.Checked, new { @class = "form-control chk" })
                        <label class="control-label chk_label" for="XuanChuan_Checked"></label>
                        @Html.LabelFor(m => m.XuanChuan, new { @class = "control-label" })
                    </div>
                    <div class="zhiyuan-p col-md-3 col-sm-6 col-xs-12">
                        @Html.CheckBoxFor(m => m.ShiWu.Checked, new { @class = "form-control chk" })
                        <label class="control-label chk_label" for="ShiWu_Checked"></label>
                        @Html.LabelFor(m => m.ShiWu, new { @class = "control-label" })
                    </div>
                </div>
                <div class="form-group" id="submit">
                    <div class="col-md-offset-1 col-md-2">
                        <input type="submit" class="btn btn-default" value="提交" />
                    </div>
                </div>
            }
        </div>
    </div>
</div>